/* ================================================================
   ТРЕКИ — редактируй только этот блок!

   ПЕРЕМЕННЫЕ КАРТОЧКИ:
     music          → файл музыки
     cover          → файл обложки
     character      → имя персонажа (крупный текст над обложкой)
     title          → название трека (мелкий текст под сердечком)

   ЦВЕТА КАРТОЧКИ:
     cardColor      → фон карточки
     btnColor       → фон кнопки play
     btnText        → иконка внутри кнопки play (треугольник/пауза)
     charColor      → цвет имени персонажа
     titleColor     → цвет названия трека
     skipColor      → цвет стрелок пред/след и иконки громкости
     progressBg     → задняя линия прогресс-бара (пустая часть)
     progressFill   → заполненная часть прогресс-бара и сердечко-ползунок
     timeColor      → цвет таймеров (0:00 / 0:00)
     modeColor      → цвет иконок шафл и повтор (неактивное состояние)
     popupBg        → фон попапа громкости
     popupBorder    → контур попапа громкости
     popupTrack     → задняя линия слайдера громкости
     popupThumb     → ползунок слайдера громкости
     creditName     → цвет имён художника и музыканта
     creditLabel    → цвет подписей "Art by" / "Music by"

   СЕРДЕЧКО:
     heartDefault   → форма SVG нелайкнутого сердца: "down" (обычное) или "up" (перевёрнутое)
     heartUnliked   → (опционально) картинка вместо SVG когда не лайкнуто, например "heart_empty.png"
                      если не указано или пусто — используется SVG из heartDefault
     heartLiked     → картинка лайкнутого сердца: "heart1.png", "heart2.png" и т.д.
     heartColor     → цвет контура SVG сердца (используется только если heartUnliked не указан)
     heartSize      → размер иконки сердца в пикселях (применяется к лайкнутой и нелайкнутой форме), по умолчанию 36
================================================================ */
const TRACKS = [
  {
    music:         "mondaymania.m4a",
    cover:         "cover1.gif",
    character:     "Sansfield",
    title:         "Mondaymania",
    cardColor:     "#ffffff",
    btnColor:      "#EE670D",
    btnText:       "#ffffff",
    charColor:     "#000000",
    titleColor:    "rgba(0,0,0,0.4)",
    skipColor:     "rgba(0,0,0,0.35)",
    progressBg:    "rgba(0,0,0,0.12)",
    progressFill:  "#EE670D",
    timeColor:     "rgba(0,0,0,0.38)",
    modeColor:     "rgba(0,0,0,0.35)",
    popupBg:       "#ffffff",
    popupBorder:   "rgba(0,0,0,0.15)",
    popupTrack:    "rgba(0,0,0,0.12)",
    popupThumb:    "#EE670D",
    creditName:    "rgba(0,0,0,0.85)",
    creditLabel:   "rgba(0,0,0,0.5)",
    heartUnliked:  "heart1_empty.png",
    heartDefault:  "up",
    heartLiked:    "heart1.png",
    heartColor:    "#000000",
    heartSize:     36,
    artName:       "Бабуля Лютик",
    artUrl:        "https://t.me/buttercupCD",
    musicName:     "aytanner",
    musicUrl:      "https://www.youtube.com/watch?v=5kt2nZ8QUVo&list=RD5kt2nZ8QUVo&start_radio=1",
    auName:        "sdfsdf",
    auUrl:         "",
  },
  {
    music:         "Underverse OST - Rekindle.m4a",
    cover:         "cover2.png",
    character:     "X!Gaster",
    title:         "Underverse OST - Rekindle",
    cardColor:     "#221F28",
    btnColor:      "#7C6994",
    btnText:       "#221F28",
    charColor:     "#7C6994",
    titleColor:    "rgba(124,105,148,0.6)",
    skipColor:     "#605c63",
    progressBg:    "rgba(255,255,255,0.12)",
    progressFill:  "#7C6994",
    timeColor:     "rgba(255,255,255,0.38)",
    modeColor:     "#605c63",
    popupBg:       "#221F28",
    popupBorder:   "#605c63",
    popupTrack:    "#605c63",
    popupThumb:    "#7C6994",
    creditName:    "rgba(255,255,255,0.92)",
    creditLabel:   "rgba(255,255,255,0.5)",
    heartUnliked:  "",
    heartDefault:  "up",
    heartLiked:    "heart2.png",
    heartColor:    "#7C6994",
    heartSize:     36,
    artName:       "джекич йоу.",
    artUrl:        "https://t.me/nevermorerrrjack",
    musicName:     "NyxTheShield",
    musicUrl:      "https://www.youtube.com/watch?v=h2MTvNBsgl4&list=RDh2MTvNBsgl4&start_radio=1",
    auName:        "sdfsdf",
    auUrl:         "",
  },
  {
    music:         "reaper.m4a",
    cover:         "cover3.png",
    character:     "Reaper",
    title:         "ReaperTale Megalovania",
    cardColor:     "#151A1F",
    btnColor:      "#4EC9CE",
    btnText:       "#151A1F",
    charColor:     "#4EC9CE",
    titleColor:    "rgba(78,201,206,0.6)",
    skipColor:     "#434C55",
    progressBg:    "rgba(255,255,255,0.12)",
    progressFill:  "#4EC9CE",
    timeColor:     "rgba(255,255,255,0.38)",
    modeColor:     "#434C55",
    popupBg:       "#151A1F",
    popupBorder:   "#434C55",
    popupTrack:    "#434C55",
    popupThumb:    "#4EC9CE",
    creditName:    "rgba(255,255,255,0.92)",
    creditLabel:   "rgba(255,255,255,0.5)",
    heartUnliked:  "",
    heartDefault:  "up",
    heartLiked:    "heart3.png",
    heartColor:    "#4EC9CE",
    heartSize:     36,
    artName:       "Тундра",
    artUrl:        "https://t.me/tendremur",
    musicName:     "Fire Music",
    musicUrl:      "https://www.youtube.com/watch?v=iAKsg3xGYek",
    auName:        "sdfsdf",
    auUrl:         "",
  },
  {
    music:         "Lustalovania.m4a",
    cover:         "cover4.png",
    character:     "Lust",
    title:         "Lustalovania",
    cardColor:     "#3C1D86",
    btnColor:      "#9CF1F6",
    btnText:       "#3C1D86",
    charColor:     "#9CF1F6",
    titleColor:    "#9CF1F6",
    skipColor:     "#96319F",
    progressBg:    "#96319F",
    progressFill:  "#9CF1F6",
    timeColor:     "rgba(255,255,255,0.38)",
    modeColor:     "#96319F",
    popupBg:       "#3C1D86",
    popupBorder:   "#96319F",
    popupTrack:    "#96319F",
    popupThumb:    "#9CF1F6",
    creditName:    "#9CF1F6",
    creditLabel:   "#9CF1F6",
    heartUnliked:  "",
    heartDefault:  "down",
    heartLiked:    "heart1.png",
    heartColor:    "#9CF1F6",
    heartSize:     36,
    artName:       "Karra",
    artUrl:        "https://t.me/Directors_02",
    musicName:     "GrowlingPanda",
    musicUrl:      "https://www.youtube.com/watch?v=B4TpEPRah4Q",
    auName:        "sdfsdf",
    auUrl:         "",
  },
  {
    music:         "Mismatch.mp3",
    cover:         "cover5.png",
    character:     "Error",
    title:         "Mismatch",
    cardColor:     "#10142D",
    btnColor:      "#A20A00",
    btnText:       "#10142D",
    charColor:     "#FDBD03",
    titleColor:    "rgba(253,189,3,0.6)",
    skipColor:     "#FDBD03",
    progressBg:    "rgba(255,255,255,0.12)",
    progressFill:  "#A20A00",
    timeColor:     "rgba(255,255,255,0.38)",
    modeColor:     "#FDBD03",
    popupBg:       "#10142D",
    popupBorder:   "#FDBD03",
    popupTrack:    "rgba(253,189,3,0.3)",
    popupThumb:    "#A20A00",
    creditName:    "rgba(255,255,255,0.92)",
    creditLabel:   "rgba(255,255,255,0.5)",
    heartUnliked:  "",
    heartDefault:  "up",
    heartLiked:    "heart5.png",
    heartColor:    "#0508AD",
    heartSize:     36,
    artName:       "Nera_7",
    artUrl:        "https://t.me/unlandd",
    musicName:     "NyxTheShield",
    musicUrl:      "https://www.youtube.com/watch?v=HeTR6Rt3WNs&list=RDHeTR6Rt3WNs&start_radio=1",
    auName:        "sdfsdf",
    auUrl:         "",
  },
  {
    music:         "waiting_for_you.m4a",
    cover:         "cover6.png",
    character:     "Error and Ink",
    title:         "Waiting For You",
    cardColor:     "#0c0c16",
    btnColor:      "#6b67dd",
    btnText:       "#0c0c16",
    charColor:     "#6b67dd",
    titleColor:    "#6b67dd",
    skipColor:     "#353362",
    progressBg:    "#353362",
    progressFill:  "#6b67dd",
    timeColor:     "#353362",
    modeColor:     "#353362",
    popupBg:       "#0c0c16",
    popupBorder:   "#353362",
    popupTrack:    "#353362",
    popupThumb:    "#6b67dd",
    creditName:    "#6b67dd",
    creditLabel:   "#6b67dd",
    heartUnliked:  "heart6_empty.png",
    heartDefault:  "down",
    heartLiked:    "heart6.png",
    heartColor:    "#e63950",
    heartSize:     48,
    artName:       "acrolein",
    artUrl:        "https://t.me/acro_ein",
    musicName:     "NyxTheShield",
    musicUrl:      "https://www.youtube.com/watch?v=bxbYUOWZZIs&list=RDx3Z5iyJ-gBg&index=5",
    auName:        "ssdfd",
    auUrl:         "",
  },
  {
    music:         "birdtale.m4a",
    cover:         "cover7.png",
    character:     "Bird",
    title:         "Birdtale - Megalovania",
    cardColor:     "#424E64",
    btnColor:      "#B7C6E7",
    btnText:       "#424E64",
    charColor:     "#93B7EB",
    titleColor:    "#738ccc",
    skipColor:     "#737F97",
    progressBg:    "#526373",
    progressFill:  "#8FB8EE",
    timeColor:     "#67768B",
    modeColor:     "#737F97",
    popupBg:       "#5F6975",
    popupBorder:   "#7E8DA0",
    popupTrack:    "#A2B0CB",
    popupThumb:    "#8A98BF",
    creditName:    "#738ccc",
    creditLabel:   "#b4c4dd",
    heartUnliked:  "",
    heartDefault:  "up",
    heartLiked:    "heart7.png",
    heartColor:    "#95B6EC",
    heartSize:     36,
    artName:       "MORI",
    artUrl:        "https://t.me/RiWasHere ",
    musicName:     "The Team Players",
    musicUrl:      "https://www.youtube.com/watch?v=QRZ3JOVI8T4",
    auName:        "Star Somsatang",
    auUrl:         "",
  },
  {
    music:         "eyes_of_a_killer.m4a",
    cover:         "cover8.png",
    character:     "Killer",
    title:         "Eyes of a Killer",
    cardColor:     "#270d0d",
    btnColor:      "#d12525",
    btnText:       "#270d0d",
    charColor:     "#d12525",
    titleColor:    "#d12525",
    skipColor:     "#574242",
    progressBg:    "#574242",
    progressFill:  "#d12525",
    timeColor:     "#d12525",
    modeColor:     "#574242",
    popupBg:       "#270d0d",
    popupBorder:   "#574242",
    popupTrack:    "#574242",
    popupThumb:    "#d12525",
    creditName:    "#d12525",
    creditLabel:   "#d12525",
    heartUnliked:  "heart8_empty.png",
    heartDefault:  "up",
    heartLiked:    "heart8.png",
    heartColor:    "#95B6EC",
    heartSize:     36,
    artName:       "KillerVtomate",
    artUrl:        "https://t.me/KillerVtomate",
    musicName:     "xXtha",
    musicUrl:      "https://www.youtube.com/watch?v=DJemBb0IsEw",
    auName:        "sdfsd",
    auUrl:         "",
  },
];